baseURL = 'https://kwholley63.github.io/being-kevin/'
locale = 'en-us'
title = 'Being Kevin'

[taxonomies]
  tag = 'tags'
  category = 'categories'

[params.postImages]
  "Daily Prompt" = "images/Daily-Prompt.jpg"
  "Book Review" = "images/Book-Review.jpg"
  "Coffee With Kevin" = "images/Coffee-With-Kevin.png"
  "Daily News" = "images/Daily-News.png"
  "Satire & Gripes" = "images/Satire-and-Gripes.png"
  "Thinking Out Loud" = "images/Thinking-Out-Loud.jpg"
  "History" = "images/history.jpg"
  "Weekly Picks" = "images/Weekly-Picks.jpg"
  "Weekly Roundup" = "images/Weekly-RoundUp.jpg"
  "Personal" = "images/Coffee-With-Kevin.png"